#!/usr/bin/env bash
# Do a full installation from scratch.
# Note: If you update this file, update .github/workflows/ci.yml also.

set -e

make install

if [ -f /etc/os-release ]
then
    os_id=$(grep -E "^ID=" /etc/os-release | sed -E "s/^ID=(.*)$/\\1/")
    case "$os_id" in
        'debian' | 'ubuntu')
        sudo make apt
        sudo make npm
        make linux-conda
        ;;
    esac
elif [[ $(uname) == 'Darwin' ]]
then
    make brew-cli
    make brew
    make npm
    make macos-conda
fi
