#!/usr/bin/env bash
set -e
scriptdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>&1 > /dev/null && pwd)

# Disable shellcheck warning for reading words instead of lines
# shellcheck disable=SC2013
for file in $(cat "$scriptdir/dotfiles.txt")
do
    rm -f "$HOME/$file"
done

rm -rf "$HOME/.bin-override"
