#!/usr/bin/env bash

scriptdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>&1 > /dev/null && pwd)
packages=$(cat "$scriptdir/apt-packages.txt")

for package in $packages
do
    # `apt` is not recommended for use in scripts because it does not have a stable CLI.
    apt-get install --yes "$package"
done
