#!/usr/bin/env bash
set -e
scriptdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>&1 > /dev/null && pwd)

install_url="$1"
if [ -z "$install_url" ]
then
    this_file=$(basename "$0")
    echo "Usage: $this_file [miniconda_download_url]" >&2
    exit 1
fi

# Download conda
downloads="$HOME/Downloads"
if [ ! -d "$downloads" ]
then
    mkdir -p "$downloads"
fi

install_script="$downloads/install_miniconda.sh"
curl -L "$install_url" -o "$install_script"
chmod +x "$install_script"

# Install conda
conda_prefix="$HOME/miniconda"
"$install_script" -b -p "$conda_prefix"
rm "$install_script"

# Install Anaconda packages
PATH="$conda_prefix/condabin:$PATH"
conda install python --yes
conda install --file "$scriptdir/anaconda-packages.txt" --yes

# Add conda and packages to PATH
conda init
conda config --set auto_activate_base false

# I don't want the base environment activated by default,
# so add the `bin` directory to PATH.
# Note that activating a conda environment does more than just set PATH.
# Packages can run scripts on environment activation as well.
# But for the things I install globally, it shouldn't really matter.
echo "PATH=\"$conda_prefix/bin:\$PATH\"" >> ~/.bash_profile.plugins
